### ISSUE TITLE
Добавить getDialogs

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rvkstat#1]
Здравствуйте. Есть ли возможность добавить в пакет getDialogs? 
Объясняю для чего: я бы хотел помечать диалоги которые привели к заявкам из лички сообщества как важные (important), а в power bi выгружать их количество. В итоге это поможет решить вопрос в автоматизацией подсчета заявок из лички.

**Comment by selesnow** [comment]
Идея интересная.
Постараюсь в ближайшее время её реализовать, как только функция будет добавлена в пакет я сообщу об этом в этой ветке.

**Comment by selesnow** [comment]
Начал работу над функцией, получил результат, но я так понял что возвращается не вся цепочка сообщений из диалога, а только последнее сообщение.
https://vk.com/dev/messages.getDialogs?params[count]=20&params[unread]=0&params[important]=0&params[unanswered]=0&params[v]=5.73

Вы такой результат ожидаете получить?

**Comment by Wreitlein** [comment]
Мне нужно только количество уникальных считать. 
К примеру, помечать любое сообщение в диалоге, если он завершился продажей, а потом просто выводить сумму уникальных помеченных сообщений.

**Comment by selesnow** [comment]
Тогда вполне подойдёт, думаю завтра всё доработаю и залью.

**Comment by selesnow** [comment]
Добавил в пакет 2 функции:

1. `vkGetGroupToken` - Для получения ключа доступа к сообществам.
2. `vkGetUserDialogs` - Для загрузки списка диалогов.

Подробную справку по работе функций можно получить при помощь команды help:
1. `help("vkGetGroupToken")`
2. `help("vkGetUserDialogs")`

Пример кода для загрузки списка диалогов сообществ:

```
library(rvkstat)
# Получаем ключ доступа для сообщества
group_token <- vkGetGroupToken(app_id = 111111, group_ids = 123456)

# Получаем список диалогов
message <- vkGetUserDialogs(access_token = group_token, count = 200)
```

Если надо получить список диалогов пользователя используйте ключ доступа пользователя, который можно получить с помощью функции vkGetToken.

Если это то, что вы просили то можете закрывать тикет.

**Comment by Wreitlein** [comment]
Алексей, в хэлпе ошибка в написании appId. http://joxi.ru/Y2L5qdOcna75GA.png
Забыли нижнее подчеркивание .

**Comment by Wreitlein** [comment]
Столбец дата получается в формате «1517315230», возможно ли получать его в нормально формате даты?

**Comment by selesnow** [comment]
Поправил:
![](http://img.netpeak.ua/alsey/152000375741_kiss_17kb.png)

Переустановите пакет и запросите снова данные.
`devtools::install_github('selesnow/rvkstat')`

Если всё ок закрывайте тикет.
