### ISSUE TITLE
Не работают методы

### ISSUE THREAD

**Issue by Polyfasol** [selesnow/rvkstat#11]
my_vk_community <- vkGetUserGroups(user_id=134754144,access_token="af80821129a94a02dkfjdbvirbvirtbf8c113a9bbe358bbb691647bdfe90")
 
Error in vkGetUserGroups(user_id = 134754144, access_token = "af80821129a94a020bbf6e6455e1439201b43cca635ba885076b4afbf8c113a9bbe358bbb691647bdfe90") : 
  Error 100 - One of the parameters specified was missing or invalid: count should be less than 1000
 
my_vk_fr <-vkGetUserFriends(user_id=134754144,access_token="af80821129a94a02dkfjdbvirbvirtbf8c113a9bbe358bbb691647bdfe90")
 
Error: $ operator is invalid for atomic vectors
 
Токены и id изменены

**Comment by selesnow** [comment]
Добрый день, исправил ошибку, установите актуальную версию пакета т.е. rvkstat 2.5.1 и функция будет корректно работать.

Для установки актуальной версии пакета запустите следующий код:

`devtools::install_github("selesnow/rvkstat")`

**Comment by max-kalganov** [comment]
Здравствуйте, у меня версия rvkstat 2.5.6. Установлено все на ubuntu 20.04.1 (если эта информация нужна). 

Функция vkGetUserFriends выдает ошибку аналогично примеру выше. vkGetUserGroups работает согласно описанию.
Прошу поправить, спасибо.
