### ISSUE TITLE
Функция vkGetAds: некорректно работает фильтр по campaign_ids

### ISSUE THREAD

**Issue by IgorMaltsev** [selesnow/rvkstat#13]
Алексей, здравствуйте.
При попытке отфильтровать получаемый список объявлений с помощью заранее сформированного вектора campaign_ids функция возвращает:

`Warning message:
In if (campaign_ids != "null") { :
  the condition has length > 1 and only the first element will be used`

При этом подстановка одного из значений campaign_id отрабатывает корректно.

**Comment by selesnow** [comment]
Добрый, на самом деле это всего лишь предупреждение т.е. Warning, при этом функция должна всё равно отработать корректно.

Доработал код и этого предупреждения уже не будет, пробуйте обновить пакет и заново загрузить список объявлений.

Код для обновления пакета:
`devtools::install_github('selesnow/rvkstat')`

**Comment by IgorMaltsev** [comment]
Спасибо!
После обновления пакета постоянно выскакивает ошибка:

`Error in fetch(key) : 
  lazy-load database 'D:/Documents/R/win-library/3.4/rvkstat/help/rvkstat.rdb' is corrupt`

**Comment by IgorMaltsev** [comment]
Спасибо большое! Тикет закрываю
