### ISSUE TITLE
Ошибка в vkGetAdStatistics

### ISSUE THREAD

**Issue by grkhr** [selesnow/rvkstat#17]
Request-URI Too Long (HTTP 414).

Запрос:
vkGetAdStatistics(account_id = XXXXXXXX,
                                       ids_type = "ad",
                                       ids = vkAds$id,
                                       period = "day",
                                       date_from = startDate,
                                       date_to = endDate,
                                       access_token = vk_token)

в vkAds$id 551 айдишник

**Comment by grkhr** [comment]
Так и делал, только по 400. Было бы круто это когда-нибудь в самом пакете написать, чтоб бил по 100. 
Спасибо!

**Comment by selesnow** [comment]
Сделаю, постараюсь в ближайшее время

**Comment by selesnow** [comment]
Походу ты сам это решил, а я уже залил твои обновления в пакет.
