### ISSUE TITLE
Ошибка в переменной join_rate

### ISSUE THREAD

**Issue by nekrasovdy** [selesnow/rvkstat#18]
Невооруженным взглядом видно, что значения переменной join_rate, возвращаемой из статистики по кампаниям и объявлениям, не соответствует данным в VK.

**Comment by selesnow** [comment]
Добрый день, извиняюсь за долгий ответ, последние несколько месяцев был занят записью курса ["Язык R для интернет маркетинга"](https://learn.needfordata.ru/r).

В ноября у меня запланирована командировка, выступление на матемаркетинге, 2 вебинара, и ещё выступление на ICamp в начале декабря, плюс довольно большая загрузка по своим внутренним задачам, поэтому сложно точно сказать когда будет время поработать по тикетам, но обещаю вашим тикетом заняться в первую очередь.

От вас надо
1. Пример кода.
2. Показать что возвращает функция.
3. Показать что в интефейсе ВК.

Названия рекламных кампаний и все остальные показатели кроме того который расчитывается не верно можно замазать, так мне будет проще разобраться в проблеме.

**Comment by nekrasovdy** [comment]
Добрый день!

Вот код. Тут все стандартно:

library(rvkstat)

camp <- vkGetAdCampaigns(account_id = ,
client_id = ,
access_token = "")

vk_stat_by_campaign <- vkGetAdStatistics(account_id = ,
ids_type = "campaign",
ids = camp$id,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")

ads <- vkGetAds(account_id = ,
client_id = ,
access_token = "")

total_frame <- data.frame()
total <- length(ads$id)
start_id <- 1
step <- 100
while (start_id <= total) {
if (start_id + step > total) step <- total - start_id
ids <-   ads$id[start_id:(start_id + step)]
temp <- vkGetAdStatistics(account_id = ,
ids_type = "ad",
ids = ids ,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")
start_id <- start_id + step + 1
total_frame <- rbind(total_frame, temp)
Sys.sleep(3)
}

Возьмем одно из самых объявлений. Вот что видим в BI. Join rate у него не хочет считаться никак.
![2018-11-12 20 57 47](https://user-images.githubusercontent.com/44200844/48358966-c13ce100-e6bd-11e8-9734-d3ebb21815d2.png)

А вот что видим в рекламном кабинете:
![screenshot_2018-11-12](https://user-images.githubusercontent.com/44200844/48358974-c6019500-e6bd-11e8-9356-609975544b2e.png)

**Comment by nekrasovdy** [comment]
Добрый день!

Вот код. Тут все стандартно:

library(rvkstat)

camp <- vkGetAdCampaigns(account_id = ,
client_id = ,
access_token = "")

vk_stat_by_campaign <- vkGetAdStatistics(account_id = ,
ids_type = "campaign",
ids = camp$id,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")

ads <- vkGetAds(account_id = ,
client_id = ,
access_token = "")

total_frame <- data.frame()
total <- length(ads$id)
start_id <- 1
step <- 100
while (start_id <= total) {
if (start_id + step > total) step <- total - start_id
ids <-   ads$id[start_id:(start_id + step)]
temp <- vkGetAdStatistics(account_id = ,
ids_type = "ad",
ids = ids ,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")
start_id <- start_id + step + 1
total_frame <- rbind(total_frame, temp)
Sys.sleep(3)
}

Возьмем одно из самых объявлений. Вот что видим в BI. Join rate у него не хочет считаться никак.
![2018-11-12 20 57 47](https://user-images.githubusercontent.com/44200844/48358966-c13ce100-e6bd-11e8-9734-d3ebb21815d2.png)

А вот что видим в рекламном кабинете:
![screenshot_2018-11-12](https://user-images.githubusercontent.com/44200844/48358974-c6019500-e6bd-11e8-9356-609975544b2e.png)

**Comment by nekrasovdy** [comment]
Алексей, буду Вам очень признателен, если поможете решить проблему в ближайшее время. Поскольку оценка эффективности привлечения РК – самая важная метрика для нас. Так что будем ждать с нетерпением. Спасибо!

**Comment by selesnow** [comment]
Вы случайно закрыли тикет, я только вернулся с командировки, и завтра постараюсь разобраться с этой проблемой.

**Comment by nekrasovdy** [comment]
Удалось разобраться?

**Comment by selesnow** [comment]
Дико извиняюсь но в самом деле у меня очень высокий загруз по рабоче, на не критические ошибки не хватает времени, мне сейчас сложно точно прогнозировать когда будет время решить эту проблему, да и я не уверен что проблема в пакете а не в самом API.

**Comment by selesnow** [comment]
ещё, на скринах не видно за какой период данные в аккаунте , скрин работы скрипта у вас из power bi, а не из RStudio, т.е. может проблема вообще в power bi, а не в r.

**Comment by selesnow** [comment]
И, у меня работает корректно:
аккаунт ВК:
![](http://imagizer.imageshack.com/img921/6941/KVaQG5.png)

RStudio
![](http://imagizer.imageshack.com/img924/4703/z3GOJG.png)

Из [справки](https://vk.com/dev/ads.getStatistics) ВК
> join_rate (если ids_type равен ad или campaign) — вступления в группу, событие, подписки на публичную страницу или установки приложения (только если в объявлении указана прямая ссылка на соответствующую страницу ВКонтакте)

Судя по всему join_rate не рассчитывается за текущий день в самом API.

**Comment by nekrasovdy** [comment]
> ещё, на скринах не видно за какой период данные в аккаунте , скрин работы скрипта у вас из power bi, а не из RStudio, т.е. может проблема вообще в power bi, а не в r.

Период был одинаковый (до определенной "сегодняшней" даты). То есть разницы из-за дат не может быть.


> только если в объявлении указана прямая ссылка на соответствующую страницу ВКонтакте

А если в посте нет ссылки как таковой? То есть это, например, обычная универсальная запись с фотографиями и текстом. Ну например.


> Судя по всему join_rate не рассчитывается за текущий день в самом API.

А у Вас по всем РК join rate корректный?

**Comment by selesnow** [comment]
Тут проблема в том, что и мне тестить особо не на чем, я территориально в украине нахожусь, у нас вк заблочили, и сейчас там практически ничего не крутится.

Попробуйте написать в поддержку API Вконтакте, может они прояснят в чём проблема может быть?
А вы мне их ответ сюда потом отправьте, если это потребуется конечно. 

Дело в том, что пакет то всего лишь парсит полученный результат, на сам результат он не влияет.

**Comment by selesnow** [comment]
СТОП!

> А если в посте нет ссылки как таковой? То есть это, например, обычная универсальная запись с фотографиями и текстом. Ну например.

А какой же тогда у неё может быть join rate? Ведь join rate показывает вступления в группу, событие, подписки на публичную страницу или установки приложения.

Инфо из официальной справки.

> join_rate (если ids_type равен ad или campaign) — вступления в группу, событие, подписки на публичную страницу или установки приложения (только если в объявлении указана прямая ссылка на соответствующую страницу ВКонтакте)

В вашем случае нет ссылки, и соответственно никакого join rate по нему и быть не может. И это проблема овсем не в пакете и не в API, а в том, что вы неправильно поняли смысл показателя.

**Comment by selesnow** [comment]
Тикет закрываю, т.к. с некорректной работой пакета он не связан.
