### ISSUE TITLE
Ошибка при обновлении данных

### ISSUE THREAD

**Issue by nekrasovdy** [selesnow/rvkstat#19]
При обновлении данных в дашборде (с помощью кнопки "Обновить") появляется ошибка про Flood

В дашборд загружены:
- список кампаний
- список объявлений
- статистика кампаний по дням
- статистика объявления по дням (версия запроса с циклом)
- общая статистика по сообществу

Ошибка появляется применительно к первой в очереди таблице.

Как обновлять данные без ошибок? Спасибо

**Comment by nekrasovdy** [comment]
library(rvkstat)

camp <- vkGetAdCampaigns(account_id = 1900013468,
client_id = 1604635899,
access_token = "b5e698b8f1de8053622873b6c2c0dc44b4e5ca35354f3b1385d4849ea12fc993bec75f14706f9c0beeeb5")

vk_stat_by_campaign <- vkGetAdStatistics(account_id = 1900013468,
ids_type = "campaign",
ids = camp$id,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "b5e698b8f1de8053622873b6c2c0dc44b4e5ca35354f3b1385d4849ea12fc993bec75f14706f9c0beeeb5")

ads <- vkGetAds(account_id = 1900013468,
client_id = 1604635899,
access_token = "b5e698b8f1de8053622873b6c2c0dc44b4e5ca35354f3b1385d4849ea12fc993bec75f14706f9c0beeeb5")

total_frame <- data.frame()
total <- length(ads$id)
start_id <- 1
step <- 100
while (start_id <= total) {
if (start_id + step > total) step <- total - start_id
ids <-   ads$id[start_id:(start_id + step)]
temp <- vkGetAdStatistics(account_id = 1900013468,
ids_type = "ad",
ids = ids ,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "b5e698b8f1de8053622873b6c2c0dc44b4e5ca35354f3b1385d4849ea12fc993bec75f14706f9c0beeeb5")
start_id <- start_id + step + 1
total_frame <- rbind(total_frame, temp)
Sys.sleep(3)
}

communityData <- vkGetGroupStat(date_from = "2018-01-01", 
date_to = Sys.Date(), 
group_id = 84987113, 
access_token = "b5e698b8f1de8053622873b6c2c0dc44b4e5ca35354f3b1385d4849ea12fc993bec75f14706f9c0beeeb5")

**Comment by selesnow** [comment]
Добрый день, обновите пакет до версии 2.5.4, данная ошибка уже исправлена.

Подробности [тут](https://github.com/selesnow/rvkstat/releases/tag/2.5.4).

Если ваша проблема после обновления решиться, прошу закрыть тикет.

**Comment by nekrasovdy** [comment]
Если в PBI запускать одновременно запросы на:
camp
ads
total_frame
communityDate
vkstatbycampaign

То все равно выдает ошибку. Говорит про Flood при формировании total_frame и другие не подружает из-за того, что все задачи не выполнены. Как-то так

**Comment by grkhr** [comment]
В вк есть ограничение на 5 запросов в секунду, вот оно и вылазит. Последнее обновление исключает ошибки внутри функции статистики, но если хотите вызывать сразу 5 одновременно - делайте очередь между ними. Код будет примерно такой (да, теперь не обязательно разбивать на айдишники по 100, так что ваш totalframe можно сократить – последнее обновление само разбивает)

`library(rvkstat)

camp <- vkGetAdCampaigns(account_id = ,
client_id = ,
access_token = "")

vk_stat_by_campaign <- vkGetAdStatistics(account_id = ,
ids_type = "campaign",
ids = camp$id,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")

Sys.sleep(1)
ads <- vkGetAds(account_id = ,
client_id = ,
access_token = "")

total_frame <- vkGetAdStatistics(account_id = ,
ids_type = "ad",
ids = ads$id ,
period = "day",
date_from = "2018-01-01",
date_to = Sys.Date(),
access_token = "")

Sys.sleep(3)
communityData <- vkGetGroupStat(date_from = "2018-01-01",
date_to = Sys.Date(),
group_id = ,
access_token = "")`

Возможно, придется подвигать Sys.sleep'ы. Не знаю, как у вас устроена модель данных внутри, но идея должна быть ясна

**Comment by andron23** [comment]
Добрый день!

sessionInfo() говорит, что установлена последняя версия - rvkstat_2.6.2. Однако, при попытке вызвать данный запрос в PBI, также вылетает ошибка FloodControl. Пробовал добавлять тайм-ауты, разбивать получение данных на цикл - не помогает. 

```
library(rvkstat)

##Получаем статистику по объявлениям
my_vk_ads <- vkGetAds(account_id = account_id,
                      access_token = access_token)


vk_stat_by_ads <- vkGetAdStatistics(account_id = account_id,
                                         ids_type = "ad",
                                         ids = my_vk_ads$id,
                                         period = "day",
                                         date_from = "2019-09-01",
                                         date_to = Sys.Date(),
                                         api_version = "5.124",
                                         access_token = access_token)
```

Если делать только vkGetAds, то все ок. В другом запросе делаю vkGetAdCampaigns и vkGetAdStatistics - также все ок. 

Если запускать через RStudio, то все работает ок. Подскажите, пожалуйста, может есть еще какие-то варианты?

**Comment by selesnow** [comment]
В данном случае проблема не в пакете, попробуйте добавить паузы между вызовами функций vkGetAds и vkGetAdStatistics через функцию `Sys.sleep(4)`.

**Comment by andron23** [comment]
> В данном случае проблема не в пакете, попробуйте добавить паузы между вызовами функций vkGetAds и vkGetAdStatistics через функцию `Sys.sleep(4)`.

Добрый день. 

Да, я понимаю, что с пакетом все ок. Паузы почему-то не помогли на этих нескольких устройствах :( Делал даже еще больше секунд.

**Comment by selesnow** [comment]
А если попробовать уменьшить период, за который вы статистику запрашиваете?

**Comment by selesnow** [comment]
Подскажите а вы одним скриптом грузите сразу 2 таблицы в Power BI?

**Comment by andron23** [comment]
> Подскажите а вы одним скриптом грузите сразу 2 таблицы в Power BI?

Добрый день!

Таблицы, которые получаются с помощью vkGetAds и vkGetAdStatistics, да, одним скриптом загружаю. Я же в качестве аргумента vkGetAdStatistics передают id-шники из vkGetAds.

**Comment by andron23** [comment]
> А если попробовать уменьшить период, за который вы статистику запрашиваете?

Вроде не помогало, но попробую еще разок. Странно еще, что на разных машинах по-разному работает...

**Comment by selesnow** [comment]
Дело в том, что я недавно выступал с темой как грузить данные в Power BI из вконтакте. 

Если вы загружаете одним скриптом много таблиц, и все их тянете в модель данных Power BI то получается в любом раскладе ошибку по лимитам. 

А если вы в ходе скрипта кидаете два запроса, поставите между ними паузу, и заберёте в модель данных только конечную таблцу, в вашем примере `vk_stat_by_ads`, то всё должно работать. 

Видео моего доклада с ближайшем будущем на моём youtube канале будет, думаю на следующей неделе.

**Comment by andron23** [comment]
> Дело в том, что я недавно выступал с темой как грузить данные в Power BI из вконтакте.
> 
> Если вы загружаете одним скриптом много таблиц, и все их тянете в модель данных Power BI то получается в любом раскладе ошибку по лимитам.
> 
> А если вы в ходе скрипта кидаете два запроса, поставите между ними паузу, и заберёте в модель данных только конечную таблцу, в вашем примере `vk_stat_by_ads`, то всё должно работать.
> 
> Видео моего доклада с ближайшем будущем на моём youtube канале будет, думаю на следующей неделе.

Может я не совсем верно понимаю: но у нас же нет другого варианта, кроме как грузить обе таблицы одним запросом? Мы же в качестве аргумента ` vkGetAdStatistics` передаем id-шники из vkGetAds. Или я не прав и нужно делать по-другому? 

Паузу между запросами ставил, не помогает. 

Видео будем ждать))

**Comment by selesnow** [comment]
Вопрос в том, далее в окне навигатора вы обе таблицы отмечаете галочками и грузите в модель данных, или грузите только `vk_stat_byads`?

**Comment by andron23** [comment]
> Вопрос в том, далее в окне навигатора вы обе таблицы отмечаете галочками и грузите в модель данных, или грузите только `vk_stat_byads`?

Да, и правда, если только таблицу `vk_stat_by_ads` грузить в модель, а `my_vk_ads `грузить потом отдельным скриптом, то все работает ок. Но это странно - не для всех таблиц такая история. Например, для рекламных кампаний все работает ок (таблицы `camp `и `vk_stat_by_campaign`). Понятно, что по ads данных больше, но у нас же все равно запрос к API делается, чтобы id-шники объявлений вытащить перед тем как статистику по дням выгружать...

За помощь, в любом случае, спасибо!

**Comment by selesnow** [comment]
Отлично, в таком случае закрываю тикет.
