### ISSUE TITLE
Error 8 - Invalid request: v (version) is required

### ISSUE THREAD

**Issue by energystuff** [selesnow/rvkstat#2]
Ошибка в vkGetAdCampaigns(account_id = ****, client_id = ****,
Error 8 - Invalid request: v (version) is required
Выполнение остановлено
================
Как решить проблему? В документации не описано.

**Comment by selesnow** [comment]
Добрый день, странное поведение.

В вашем примерере я не весь код вижу, но попробуйте сделать следующее).

`camp <- vkGetAdCampaigns(account_id = ****, client_id = ****, access_token = ***, api_version = "5.73")`

Если всё получится то просьба закрыть тикет, если нет то скиньте сюда ваш код без токено и номеров аккаунтов, и сообщение об ошибке которую получите.

И ещё вопрос, какая у вас операционная система?

**Comment by energystuff** [comment]
=====
Не получилось!
=====

library(rvkstat)
#Получаем список рекламных кампаний
my_vk_campaigns <- vkGetAdCampaigns(account_id = ***, 
                                    client_id = ***,
                                    api_version = "5.73",
                                    access_token = "***")
									
##Получаем статистику по рекламным кампаниям по дням
vk_stat_by_campaign <- vkGetAdStatistics(account_id = ***,
                                        ids_type = "campaign",
                                        ids = my_vk_campaigns$id,
                                        period = "day",
                                        date_from = "2010-01-01",
                                        date_to =Sys.Date(),
                                        access_token = "***")

**Comment by selesnow** [comment]
А какую ошибку вы в консоли получаете при исполнении этого кода?

**Comment by energystuff** [comment]
ADO.NET: Ошибка сценария R.

---------------------
Добро паловать в rvkstat версии 2.1.4

Описание: 
rvkstat - R клиент для упрощённой работы с API социальной сети ВКонтакте, и загрузки данных в R. 

Автор пакета: 
Алексей Селезнёв / Alexey Seleznev (Head of analytics dept at Netpeak).
Email:        selesnow@gmail.com
Блог:         https://alexeyseleznev.wordpress.com 
Facebook:     https://facebook.com/selesnown 
Linkedin:     https://www.linkedin.com/in/selesnow 

Используйте ?rvkstat для получения справки по всем доступным в пакете rvkstat функциям.
Страница пакета на github: https://github.com/selesnow/rvkstat/

Предлоджения по улучшению пакета, а так же отчёты об ошибках можно оставлять тут: https://github.com/selesnow/rvkstat/issues

	Что бы это сообщение больше не выводилось используйте команду:  suppressPackageStartupMessages(library(rvkstat))
---------------------

Ошибка в vkGetAdCampaigns(account_id = ***, client_id = ***,  :
  неиспользованный аргумент (v = "5.73")
Выполнение остановлено

**Comment by selesnow** [comment]
Теперь всё понятно:

_Добро паловать в rvkstat версии 2.1.4_

У вас старая версия пакета, установите актуальну. версию т.е. 2.4.1, для этого воспользуйтесь следующим кодом.

`devtools::install_github('selesnow/rvkstat')`

**Comment by selesnow** [comment]
Если проблема решена, закройте тикет.
