### ISSUE TITLE
Доп.показатели по объявлениям

### ISSUE THREAD

**Issue by nekrasovdy** [selesnow/rvkstat#20]
Добрый день!

Есть ли возможность добавить к статистике по объявлениям 3 показателя:
- скрыли объявление
- скрыли все записи
- оценка объявления со стороны ВК (по десятибалльной шкале)

Спасибо

**Comment by selesnow** [comment]
Добрый, подскажите о какой именно функции идёт речь?

**Comment by nekrasovdy** [comment]
vkGetAdStatistics - статистка по рекламным объявлениям по дням

**Comment by selesnow** [comment]
На данный момент [API ВК](https://vk.com/dev/ads.getStatistics) позволяет получить только следующие поля:

* day (если period равен day) — день в формате YYYY-MM-DD
* month (если period равен month) — день в формате YYYY-MM
* overall (если period равен overall) — 1
* spent — потраченные средства
* impressions — просмотры
* clicks — клики
* reach (если ids_type равен ad или campaign и period равен day или month) — охват
* video_views (если ids_type равен ad) — просмотры видеоролика (для видеорекламы)
* video_views_half (если ids_type равен ad) — просмотры половины видеоролика (для видеорекламы)
* video_views_full (если ids_type равен ad) — просмотры целого видеоролика (для видеорекламы)
* video_clicks_site (если ids_type равен ad) — переходы на сайт рекламодателя из видеорекламы (для видеорекламы)
* join_rate (если ids_type равен ad или campaign) — вступления в группу, событие, подписки на публичную страницу или установки приложения (только если в объявлении указана прямая ссылка на соответствующую страницу ВКонтакте)

**Comment by selesnow** [comment]
Пока закрываю тикет т.к. такой возможности не предоставляет API Вконтакте.
