### ISSUE TITLE
vkAuth не могу пройти аутентификацию

### ISSUE THREAD

**Issue by stavrovskaya** [selesnow/rvkstat#21]
Добрый день. 

Пытаюсь получить токен, который работает с любого ip. Делаю:
my_tok <- vkAuth(app_id = ХХХХХ,app_secret = "ХХХХХХХ")
Получаю ошибку:
{"error":"invalid_request","error_description":"redirect_uri is incorrect, check application redirect uri in the settings page"}
Настройки приложения: http://joxi.ru/L21E1wzH847PB2
В URI стоят:
https://selesnow.github.io/rvkstat/getCode/get_code.html 
https://selesnow.github.io/rvkstat/getCode/get_token.html
https://oauth.vk.com/blank.html

В чем может быть причина?

С уважением,

Елена Ставровская

**Comment by selesnow** [comment]
Судя по скрину с настройками приложения у вас всё в порядке, возможно был какой то временный глюк?
