### ISSUE TITLE
VK errors

### ISSUE THREAD

**Issue by osipsemyon** [selesnow/rvkstat#23]
Алексей, добрый день!

В пакете vkGetAds вы задаете столбцу ad_format свои нейминги, однако добавились адаптивные объявления, имеющие значение 11 и 12, которые не обрабатываются вашим пакетом. 
https://vk.com/dev/ads.getAds
тут описаны настоящие методы, включая 11-й, а также, как оказалось, узнав от техподдержки, появился 12-й формат - сторис, которого нет в этой документации, однако по апи получить его можно

**Comment by selesnow** [comment]
Обновил справочник
