### ISSUE TITLE
Не удается подключить скрипт через Power BI

### ISSUE THREAD

**Issue by skarapotin** [selesnow/rvkstat#27]
Здравствуйте!

Вводные данные:
- поскольку у меня присутствует кириллица в пути и нет возможности переименовать папку, я создал для библиотек отдельный путь C:\R\library
- установку пакета проводил через RStudio

Пакет установился, запуск сработал, токен получил. В Power BI использую при простом подключении пакета выдает ошибку, что пакет не найден. Тогда при подключении прописываю путь к библиотекам:
#Подключаем пакет
library(rvkstat, lib.loc = "C:/R/Library")

Тогда выплывает следующая ошибка:

Подробности: "ADO.NET: Ошибка сценария R.
Ошибка: package or namespace load failed for 'rvkstat':
 .onLoad не удалось в loadNamespace() для 'pillar', подробности:
  вызов: loadNamespace(name)
  ошибка: нет пакета под названием 'crayon'
Выполнение остановлено
"

Что я сделал не так?

**Comment by skarapotin** [comment]
пакет crayon установил так же в C:/R/Library

**Comment by selesnow** [comment]
После установки crayon проблема не ушла?

**Comment by skarapotin** [comment]
Нет, ведь он же установлен, я в следующем комменте дописал)

**Comment by selesnow** [comment]
Проблема только при запуске в Power BI?

Дело в том, что у R который запускает Power BI есть дополнительная библиотека, возможно она из неё пытается вытащить файл, что бы посмотреть все библиотеки попробуйте в Power BI выполнить следующий RScript.

`lib <- as.data.frame(.libPaths())`

Убедитесь что в других библиотеках нет пакета pillar и crayon, если они есть то лучше удалить их.

Ещё вам может помочь эта статья - http://blog.datainspirations.com/2018/02/02/power-bi-r-home-directory-vs-library-trees/

**Comment by skarapotin** [comment]
По команде 
lib <- as.data.frame(.libPaths())
Выдает такой путь к библиотекам:
C:\R\library\Library
Это пустая папка, все библиотеки лежат выше на C:\R\library
Пробовал вручную поменять в настройках PowerBI временное хранилище, но безрезультатно.

По второму коду пакетов pillar и crayon не находит

**Comment by skarapotin** [comment]
Все дело в регистре, по всей видимости. В коде исправил на library, теперь все работает, спасибо
