### ISSUE TITLE
Период действия токена

### ISSUE THREAD

**Issue by kseniyaDA** [selesnow/rvkstat#28]
Здравствуйте,
после успешно пройденной авторизации через **vkAuth**, получены следующие параметры токена:
![image](https://user-images.githubusercontent.com/44363173/89640452-46b3ec00-d8b8-11ea-93b3-e0fe67d36a30.png)

правильно ли я понимаю, что длительность действия токена не больше дня? и можно ли сделать, чтобы текущий токен действовал какое-то бОльшее время, например несколько месяцев или год?

**Comment by selesnow** [comment]
Здравствуйте, 0 означает что ваш токен бессрочный, т.е. будет действовать до тех пор, пока вы например не поменяете пароль, пользователю под которым этот токен получилию
