### ISSUE TITLE
Ошибка при обращении к vkGetAdPostsReach

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rvkstat#3]
[Скриншот](http://joxi.ru/brRZ83ycQ91oLr.png)

**Comment by selesnow** [comment]
Приветствую, попробуйте в функции vkGetAdPostsReach добавить аргумент api_version = 4.

**Comment by Wreitlein** [comment]
Не помогло [Скрин](http://joxi.ru/J2bq50ou49Oq9m.png)

**Comment by selesnow** [comment]
Странно сейчас пробовал воспроизвести вашу ошибку, но у меня всё работает корректно, вот мой код:

```r
library(rvkstat)
token <- vkAuth(app_id = ******, app_secret = "******")

My_Ads <- vkGetAds(
    client_id = ******,
    account_id = ******,
    access_token = token$access_token
  )

post_reach <- vkGetAdPostsReach(
    account_id = ******,
    ids_type = "ad",
    ids = My_Ads$id,
    access_token = token$access_token
  )
```

В результате чего я получаю нужные объекты:
![](http://img.netpeak.ua/alsey/152095220910_kiss_7kb.png)

Проверьте, после запуска функции vkGetAds у вас в рабочем окружении появляется объект My_Ads, содержит он хотя бы одну строку или нет, из консоли проверить наличие объекта можно с помощью команды `exists("My_Ads")`

**Comment by Wreitlein** [comment]
Ваш вариант кода выдает эту же ошибку. My_Ads содержит строки [скрин](http://joxi.ru/Drl0OwDT4lOgbr.png)

**Comment by selesnow** [comment]
Давайте проверим версию пакета, выполните команду `utils::packageDescription("rvkstat")$Version`.

**Comment by Wreitlein** [comment]
[1] "2.4.2"

**Comment by selesnow** [comment]
Странно, попробуйте протестировать запрос через веб интерфейс этого метода API.
Перейдите по ссылке - https://vk.com/dev/ads.getPostsReach
И внизу страницы будет форма для запроса.
![](http://img.netpeak.ua/alsey/152095456936_kiss_9kb.png)

**Comment by selesnow** [comment]
И ещё вопрос, account_id вы одинаковый указываете в функциях vkGetAds и vkGetAdPostsReach, проверьте на всякий случай.

**Comment by Wreitlein** [comment]
Проверил, ошибки нет. Форма: при указании конкретной кампании в поле ids выдаёт правильную статистику.[ скрин](http://joxi.ru/brRZ83ycQ9ElLr)

**Comment by selesnow** [comment]
ОК, тогда попробуйте через rvkstat запросить данные именно по этой одной кампании.

**Comment by Wreitlein** [comment]
Вот так вот [скрин](http://joxi.ru/1A5o9q0IKM7eYm.png)

**Comment by selesnow** [comment]
Честно говоря пока у меня закончились варианты, я не могу воспроизвести вашу ошибку у себя, у меня всё отрабатывает корректно, я уж показывал скрин выше.

Тут разве что возможно переустановить пакеты:utils, httr, RCurl, jsonlite, tidyr, rvkstat

Если и это не поможет, то в другом случае для того, что бы вам помочь мне нужен будет доступ к вашему аккаунту, т.к. на моих аккаунтах всё отрабатывает корректно.

**Comment by Wreitlein** [comment]
При обновлении пакета rvstat получил ошибку совместимости 
`install.packages("rvkstat")
Warning in install.packages :
package ‘rvkstat’ is not available (for R version 3.4.3)`

**Comment by selesnow** [comment]
Какая у вас операционная система?

Из какого каталога вы устанавливаете rvkstat, можно посмотреть код, как вы его пытаетесь поставить?

**Comment by Wreitlein** [comment]
Windows 10. Через `if(!"devtools" %in% installed.packages()[,1]){install.packages("devtools")}
devtools::install_github('selesnow/rvkstat')` установился. Ошибка выдавалась если пытаться установить через модуль установки библиотек в RStudio

**Comment by selesnow** [comment]
OK, после переустановки всех пакетов проблема осталась?

**Comment by Wreitlein** [comment]
Все пакеты переустановил, результат не изменился

**Comment by selesnow** [comment]
В таком случае я смогу помочь только если вы сохраните и отправите мне на почту своё рабочее окружение, при это я получу полный доступ к вашим данным.

По другому помочь не смогу т.к. все возможные варианты мы уже перебрали, и эта ошибка у меня не воспроизводится, у меня функция отрабатывает корректно.

Если что, повторите все операции включая ошибку,далее можете скинуть сохранённое рабочее пространство в виде RData файла и весь листинг кода на selesnow@gmail.com. И я уже буду более детально разбираться с причиной ошибки.

Сохранить рабочее пространство можно так:
`save.image(file = "my_workspace.RData")`

**Comment by Wreitlein** [comment]
К сожалению это невозможно, в любом случае это видимо проблема с моим ПО, тикет закрываю.

**Comment by SemyonMSKMC** [comment]
Алексей, здравствуйте
Абсолютно аналогичная ошибка
При детальном рассмотрении мы поняли, что данная ошибка возникает, если в рекламном объявлении присутствует видео формат, прямым get запросом все отлично вытаскивается, через пакет - нет
