### ISSUE TITLE
getURL, vkGetGroupStat

### ISSUE THREAD

**Issue by rdtdcdo** [selesnow/rvkstat#30]
Здравствуйте 
Можете помочь с кодом,  при запросе в PowerBI выводится ошибка 
> _Ошибка в names(x) <- value :
> атрибут 'names' [7] должен быть той же длины, что и вектор [0]
> Вызовы: vkGetGroupStat -> colnames<-
> Выполнение остановлено_
> 

А при запуске в R console:
> _Ошибка в getURL(apiQuery) :не могу найти функцию "getURL"_

сам запрос:

```
#Подключаем пакет
library(rvkstat)
##Получаем статистику 
stats <- vkGetGroupStat(group_id = "165999632",
                                        date_from = "2020-12-01", 
                                        date_to = "2020-12-03", 
                                        access_token = "d6***9a")
										

```

**Comment by selesnow** [comment]
Судя по всему вам надо доустановить пакет `RCurl`, т.к. `getURL()` именно из него берётся. Эта функция используется под капотом `vkGetGroupStat()`. 

Довольно странно что она у вас автоматом не подтянулась, т.к. я прописал её в [NAMESPACE](https://github.com/selesnow/rvkstat/blob/master/NAMESPACE#L36).
