### ISSUE TITLE
Возможность выгрузки статистики постов в сообщетсве

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rvkstat#4]
Здравствуйте. Возможно ли добавить выгрузку статистики по постам в сообществе с полями
— Количество лайков
— Количество репостов
— Количество комментариев 
— Количество просмотров поста
— Дата публикации
— Ссылка на пост
Или такая функция уже выполняется? Есть приме кода на python который выполняет эту функцию. 
[parses stat.zip](https://github.com/selesnow/rvkstat/files/1815474/parses.stat.zip)

**Comment by selesnow** [comment]
Я думаю вам подойдёт функция vkGetUserWall, она так же использует метод API [wall.get](https://vk.com/dev/wall.get).

По крайней мере она использует тот же метод API что и парсер в примере вашего Python кода.
![](http://img.netpeak.ua/alsey/152112746473_kiss_10kb.png)

[Ссылка на документацию](https://selesnow.github.io/rvkstat/#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE-%D1%81%D1%82%D0%B5%D0%BD%D1%8B-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D1%81-%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE%D0%BC-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B5%D0%B2-%D0%BB%D0%B0%D0%B9%D0%BA%D0%BE%D0%B2-%D0%B8-%D1%80%D0%B8%D0%BF%D0%BE%D1%81%D1%82%D0%BE%D0%B2)

Единственное это вам надо передать в аргумент user_id не id пользователя, а id сообщества.

Пробуйте, если нужна помощь, обращайтесь.

**Comment by Wreitlein** [comment]
Запрос проходит но в ответ прилетают пустые значения. Проверил на нескольких группах с правами администратора сообществ. [Скрин](http://joxi.ru/v29pJ0zCG56EJm.png)

**Comment by selesnow** [comment]
Сегодня уже неуспеваю проверить как работает функция, на следующей неделе обязательно проверю и отпишусь.

**Comment by Apstol** [comment]
Здравствуйте! Пытался установить пакет из R-studio через виртуальную машину гугл (система Ubuntu), и выдает такую ошибку:

Error in parse(outFile) : 
  /tmp/Rtmpmllot5/devtools7a7236afe01b/selesnow-rvkstat-21869c8/en/R/vkGetGroupStat.R:26:10: unexpected string constant
26: ubscribed")
27:   vkData$Date <- as.POSIXct(vkData$Date, format = "
             ^
ERROR: unable to collate and parse R files for package ‘rvkstat’

В чем может быть проблема?

**Comment by selesnow** [comment]
Приветсвую, смотрите в чём может быть проблема:

Тут 2 причины:
# 1 - Идентификатор группы надо указывать со знаком минус:

owner_id | идентификатор пользователя или сообщества, со стены которого необходимо получить записи (по умолчанию — текущий пользователь).Обратите внимание, идентификатор сообщества в параметре owner_idнеобходимо указывать со знаком "-" — например, owner_id=-1 соответствует идентификатору сообщества ВКонтакте API (club1)

# 2. Изменился ответ от API, поэтому пока надо принудительно указать что вы делаете запрос к старой версии API, т.е. к 4ой

Пример кода, для того что бы получить статистику по записям моей группы в ВК, статистика открыта.

```r
token <- vkAuth(app_id = 1111111, app_secret = "abcde12345")
my_vk_wall <- vkGetUserWall(user_id = -119709976,
                            access_token = token$access_token,
                            api_version = 4)
```

В ближайшее время перепишу функцию таким образом что бы она работала с наиболее актуальной версией API.

**Comment by selesnow** [comment]
Доработал функцию, теперь она корректно обращается как к старой версии API, т.е. до 5ой, так и с новой версией 5.x.

Переустановите пакет и всё будет работать корректно.
`devtools::install_github("selesnow/rvkstat")`

Результат работы функции:
![](http://img.netpeak.ua/alsey/152145961760_kiss_27kb.png)

**Comment by Wreitlein** [comment]
Спасибо за то, что не бросаете проект и активно поддерживаете его!

**Comment by Wreitlein** [comment]
А возможно забирать количество просмотров постов для подсчёта вовлеченности?

**Comment by Wreitlein** [comment]
Для power bi наверное проще будет использовать новый столбец с формулой `Ссылка = CONCATENATE("https://vk.com/wall-*сюда вписать номер группы*_"; ('my_vk_wall'[id]))`

**Comment by selesnow** [comment]
Приветсвую, постараюсь завтра всё это реализовать.

**Comment by selesnow** [comment]
Добрый день, добавил в функцию `vkGetUserWall` загрузку данных о количестве просмотров, но количество просмотров можно получить только при обращении к версии API не ранее 5.0, тогда будет возвращён столбец views.

Пример кода:
```r
library(rvkstat)      
token <- vkAuth(app_id = 111111, app_secret = "abcdef12345")
my_vk_wall2 <- vkGetUserWall(user_id = -119709976,
                             access_token = token$access_token)     
```

Структура дата фрейма который в результате вы получитет:

_'data.frame':	28 obs. of  12 variables:
 $ id             : int  28 27 26 25 24 23 22 21 20 19 ...
 $ from_id        : int  -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 ...
 $ to_id          : logi  NA NA NA NA NA NA ...
 $ date           : POSIXct, format: "2018-03-26 10:04:20" "2018-03-23 13:00:33" "2018-03-22 12:59:49" "2018-03-21 11:07:21" ...
 $ post_type      : chr  "post" "post" "post" "post" ...
 $ text           : chr  "Друзья, в Одесский офис одной из компаний в Netpeak Group нужен data scientist, если ты не задумываясь можешь н"| __truncated__ "Пожалуй все уже неоднократно слышали про Power BI, по итогам исследования \"Gartner magic quadrant business int"| __truncated__ "Порция наиполезнейших советов от Севы Мироновича для всех кто ежедневно сталкивается или планирует использовать"| __truncated__ "В пакете ryandexdirect исправлена ошибка, при использовании оператора IN при фильтрации данных в функции yadirG"| __truncated__ ...
 $ can_delete     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ views          : int  4 21 26 31 96 34 36 39 42 44 ...
 $ comments_count : int  0 0 0 0 0 0 0 0 0 0 ...
 $ likes_count    : int  0 0 0 0 1 0 0 1 0 0 ...
 $ reposts_count  : int  0 0 0 0 1 0 0 0 0 0 ...
 $ attachment_type: logi  NA NA NA NA NA NA ...
'data.frame':	28 obs. of  12 variables:
 $ id             : int  28 27 26 25 24 23 22 21 20 19 ...
 $ from_id        : int  -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 -119709976 ...
 $ to_id          : logi  NA NA NA NA NA NA ...
 $ date           : POSIXct, format: "2018-03-26 10:04:20" "2018-03-23 13:00:33" "2018-03-22 12:59:49" "2018-03-21 11:07:21" ...
 $ post_type      : chr  "post" "post" "post" "post" ...
 $ text           : chr  "Друзья, в Одесский офис одной из компаний в Netpeak Group нужен data scientist, если ты не задумываясь можешь н"| __truncated__ "Пожалуй все уже неоднократно слышали про Power BI, по итогам исследования \"Gartner magic quadrant business int"| __truncated__ "Порция наиполезнейших советов от Севы Мироновича для всех кто ежедневно сталкивается или планирует использовать"| __truncated__ "В пакете ryandexdirect исправлена ошибка, при использовании оператора IN при фильтрации данных в функции yadirG"| __truncated__ ...
 $ can_delete     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ views          : int  4 21 26 31 96 34 36 39 42 44 ...
 $ comments_count : int  0 0 0 0 0 0 0 0 0 0 ...
 $ likes_count    : int  0 0 0 0 1 0 0 1 0 0 ...
 $ reposts_count  : int  0 0 0 0 1 0 0 0 0 0 ...
 $ attachment_type: logi  NA NA NA NA NA NA ..._
