### ISSUE TITLE
Проблема с установкой пакета

### ISSUE THREAD

**Issue by Apstol** [selesnow/rvkstat#5]
Здравствуйте! Пытался установить пакет из R-studio через виртуальную машину гугл (система Ubuntu), использовал команду: if(!"devtools" %in% installed.packages()[,1]){install.packages("devtools")}
devtools::install_github('selesnow/rvkstat', subdir = "en")
Выдает такую ошибку:
Error in parse(outFile) :
/tmp/Rtmpmllot5/devtools7a7236afe01b/selesnow-rvkstat-21869c8/en/R/vkGetGroupStat.R:26:10: unexpected string constant
26: ubscribed")
27: vkData$Date <- as.POSIXct(vkData$Date, format = "
^
ERROR: unable to collate and parse R files for package ‘rvkstat’

В чем может быть проблема?

**Comment by selesnow** [comment]
Вы всё правильно делали, проблема была на стороне пакета, уже исправил, пробуйте установить, если всё ОК закрывайте тикет.
```r
if(!"devtools" %in% installed.packages()[,1]){install.packages("devtools")}
devtools::install_github('selesnow/rvkstat', subdir = "en")
```

**Comment by Apstol** [comment]
Эта ошибка прошла, а теперь выдает такое:
Error in parse(outFile) : 
  /tmp/RtmpnmbtYm/devtools8912bc3ecdb/selesnow-rvkstat-a3573a2/en/R/vkGetGroupStatAge.R:33:13: unexpected ')'
32: }
33: Age$AgeGroup)
                ^
ERROR: unable to collate and parse R files for package ‘rvkstat’

**Comment by selesnow** [comment]
Перезалил все скрипты пакета, пробуйте ещё раз установить, по идее ошибок больше не будет.

```r
if(!"devtools" %in% installed.packages()[,1]){install.packages("devtools")}
devtools::install_github('selesnow/rvkstat', subdir = "en")
```

**Comment by Apstol** [comment]
Спасибо, все загрузилось!

**Comment by Apstol** [comment]
Спасибо, все загрузилось!
