### ISSUE TITLE
Подписчики сообщества

### ISSUE THREAD

**Issue by Wreitlein** [selesnow/rvkstat#6]
Здравствуйте, сейчас  подписки и отписки выгружаются разными колонками. Для подчета подписчиков в power bi я использует (подписки - отписки) но данные доступны только в статике. Возможно есть возможность выгружать количество подписчиков на определенную дату, или можно добавить запрос вида
YYYY:MM:DD;Количество подписчиков

**Comment by selesnow** [comment]
Приветсвую, к сожалению пока такой возможности в документации я не нашел.

Функции из rvkstat о которых вы говорите работают с методом [stats.get](https://vk.com/dev/stats.get), которая возвращает только к-во новых подписчиков и к-во отписавшихся.

Наиболее вероятно другой возможности и не будет, ведь количество подписчиков это величина по своим свойствам схожа к примеру с остатками товаров, эти метрики нельзя смотреть за какой то период времени, а можно получить лишь на какой то конкретный момент времени, к примеру мы не можем узнать сколько было подписчиков у вас в январе 2018 года, т.е. кто то подписывался в течении месяца а кто то отписывался, но мы можем однозначть сказать сколько подписчиков было в сообществе к примеру на 1 января 2018 года в 00:00:00.

Поэтому в данном случае для решения вашей задачи я могу написать функцию работающую с метода [groups.getMembers](https://vk.com/dev/groups.getMembers), которая будет возвращать список и количество пользователей на тот момент времени когда эта функция будет запущена, в таком случае для отслеживания динамики вам надо будет настроить запуск скрипта по расписанию ([пошаговая инструкция для Windows](https://alexeyseleznev.wordpress.com/2016/11/17/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-r-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0-%D0%BF%D0%BE-%D1%80%D0%B0%D1%81%D0%BF%D0%B8/)) и сохранять полученную таблицу в какую то базу данных, можно BigQuery (пакет bigrquery, подробную инструкцию о том как работать с BigQuery в том числе с помощью пакета bigrquery можно найти по этой [ссылке](https://alexeyseleznev.wordpress.com/2017/11/10/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%87%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D1%82%D1%8C-%D1%81-google-bigquery/)), можно MySQL для этого надо использовать пакет RMySQL или RMariaDB.

И уже на основе этих собранных данных вы сможете вывести динамику изменения количества подписчиков.

**Comment by Wreitlein** [comment]
Спасибо за столь развернутый ответ. Думаю данный костыль принесёт больше работы чем пользы, пока в новой функции нет необходимости. Спасибо. 
А есть говорить про power bi. Возможно ли написать формулу котороая будет sum(подписчики за весь прошлый период начиная с начала данных) - sum(отписки подписчики за весь прошлый период начиная с начала данных) и выводить на каждой строчке полученные данные

**Comment by selesnow** [comment]
> А есть говорить про power bi. Возможно ли написать формулу котороая будет sum(подписчики за весь прошлый период начиная с начала данных) - sum(отписки подписчики за весь прошлый период начиная с начала данных) и выводить на каждой строчке полученные данные

В общем можно хоть и немного костыльно, формула для создания пользовательского столбца:
```dax
Subscribers = //Считаем количество подписавшихся за прошлый период
              SUMX(FILTER(group_data; 
                              EARLIEST(group_data[Date]) > group_data[Date]); 
                          group_data[Subscribed]) - 
              //Считаем количество отписавшихся за прошлый период
              SUMX(FILTER(group_data; 
                              EARLIEST(group_data[Date]) > group_data[Date]); 
                          group_data[Unsubscribed])
```

С помощью функции EARLIEST мы сверяем дату в текущей строке, и фильтруем всю таблицу по условию что должны оставаться для расчёта только строки которые имеют более раннюю дату.

Результат выглядит вот так:

![](http://img.netpeak.ua/alsey/152207200198_kiss_45kb.png)

**Comment by Wreitlein** [comment]
Огромное вам спасибо!

**Comment by Wreitlein** [comment]
Алексей, при попытки воспользоваться вашей формулой power bi ругается 
![31c2a08352](https://user-images.githubusercontent.com/36955869/37913709-3208d750-311e-11e8-885a-e8d170428c8c.png)

**Comment by selesnow** [comment]
Вместо group_data подстсвьте название вашей таблицы со статисаой группы.

**Comment by Wreitlein** [comment]
Спасибо
