### ISSUE TITLE
Реализация метода stats.getPostReach

### ISSUE THREAD

**Issue by IgorMaltsev** [selesnow/rvkstat#8]
Алексей, добрый день.
Переношу сюда свою просьбу по поводу реализации в Вашем пакете метода stats.getPostReach (https://vk.com/dev/stats.getPostReach) для получения более полной статистики публикаций.
Спасибо!

**Comment by selesnow** [comment]
Функция практически готова, думаю завтра уже окончательно её протестирую и добавлю в пакет.

**Comment by selesnow** [comment]
Готово!

В пакет добавлена функция `vkGetGroupStatPostReach`, которая работает с методом API stats.getPostReach.

*Пример работы с функцией*
```r
## Авторизация в вк
my_tok <- vkAuth(app_id = 1, app_secret = "H2Pk8htyFD8024mZaPHm")

## Получаем список сообщений сообщества
my_vk_wall  <- vkGetUserWall(user_id = -111111,
                             access_token = my_tok$access_token) 
							 
## Получаем подрубную статистику по последним 300 записям сообщества							 
post_reach <- vkGetGroupStatPostReach(owner_id = -2222222,
                                      post_ids = my_vk_wall$id,
                                      access_token = my_tok$access_token)
```

*Аргументы функции*
* owner_id - идентификатор сообщества — владельца записи. Указывается со знаком «минус».
* post_ids - векор содержащий идентификаторы записей, обратите внимание — данные по статистике доступны только для 300 последних (самых свежих) записей на стене сообщества.
* api_version - Необзательный аргумент, номер версии API к которой будет выполнен запрос.
* access_token - Токен доступа к API, полученный с помощью функций vkAuth или vkGetToken

**Подробная справка по функции**
Для получения подробного описания функции воспользуйтесь командой `help(vkGetGroupStatPostReach)`.

Если это, то что вы и просили можете закрывать тикет.

**Comment by IgorMaltsev** [comment]
Алексей, спасибо Огромное!
