### ISSUE TITLE
Детализация данных функции vkGetAdCityStats

### ISSUE THREAD

**Issue by IgorMaltsev** [selesnow/rvkstat#9]
Подскажите, возможно ли выгружать полный список городов, а не первые N? И, кстати, по какому принципу формируется выдача? Заметил, что разные запросы отдают разное количество городов.

**Comment by selesnow** [comment]
Ограничение идёт не на количество городов а на количество объявлений в одном запросе 2000, думаю проблема именно в этом.

Функция использует метод API [ads.getDemographics](https://vk.com/dev/ads.getDemographics), в общем ограничение на к-во объявлений можно обойти если разделить объявления на группы по 2000, и запрашивать по очереди каждую группу используя цикл for.

**Comment by IgorMaltsev** [comment]
Алексей, спасибо за ответ, но вряд ли дело в количестве объявлений, потому что пробовал получить данные и для одного объявления.

**Comment by egkasatkin** [comment]
@selesnow 
Алексей, возникает ошибка в функциях : vk_ad_city_stat_day, vk_ad_gender_age_stat_day
Ошибка: Error in dataRaw$response[[i]]$stats[[dt]] : subscript out of bounds
Возникает и для campaign и для ad в поле ids_type
для некоторых конткретный campign/ad (ids = camp$id[25]) работает функция, но на некоторых нет

Если нужно подробнее написать, то напишите в телеграм @scaremyself

Пример кода:
##Получаем статистику по рекламным кампаниям по дням
vk_ad_city_stat_day <- vkGetAdCityStats(account_id = ***,
                                        ids_type = "campaign",
                                        ids = camp$id[25],
                                        period = "day",
                                        date_from = staticDate, 
                                        date_to = Sys.Date()-1,
                                        api_version = "5.122",
                                        access_token = token)

##Получаем статистику по рекламным кампаниям по дням
vk_ad_gender_age_stat_day <- vkGetAdGenderAgeStats(account_id = ***,
                                                   ids_type = "ad",
                                                   ids = ad$id[51],
                                                   period = "day",
                                                   date_from = staticDate, 
                                                   date_to = Sys.Date()-1,
                                                   api_version = "5.122",
                                                   access_token = token)

**Comment by selesnow** [comment]
Пакет был почти полностью переписан, данной ошибке нет в версии 3.0.0
